### ISSUE TITLE
How to name files

### ISSUE THREAD

**Issue by justin808** [shakacode/style-guide-javascript#21]
https://github.com/airbnb/javascript/issues/1336

Per the linked issue:

Regarding this issue: https://github.com/airbnb/javascript/issues/949

I find it difficult to work in RubyMine/Webstorm with tons of files named `index.js`:

* Have to remember to hit a `/` after typing the name and autocomplete is not great
* Search results harder to read.

I'd like to suggest the following convention:

1. Create the file as `components/MyComponent/MyComponent.js`;
2. Create an "index" file in that directory with one line:
`export { default } from `./MyComponent.js`
3. Do the import as: `import MyComponent from 'components/MyComponent';` (using the default for the directory.

I believe this may give the best of both worlds in that 

1. The files are named per the default export.
2. Easier file navigation in most editors.
3. Avoid having multiple editor tabs open that say `index.js`.
4. Still have the concise import statement for the main file in a directory.

The cost is only to add the `index.js` file in each directory with a default component.

**Comment by robwise** [comment]
We already are using the same style across multiple client projects that is different than this. It would take weeks to change this now, I don't think it's worth it.

**Comment by justin808** [comment]
I'm OK with the index.js convention.
